# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleProject

  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'Moya', '~> 10.0'
  pod 'Moya/RxSwift'
  pod 'Moya-ModelMapper', '~> 6.0'
  pod 'Moya-ModelMapper/RxSwift'
  pod 'Kingfisher'
  
  target 'SimpleProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift'
    pod 'Quick'
    pod 'Nimble'
  end

end
